GET http://localhost:8888/.netlify/functions/goalsAPI

###
POST http://localhost:8888/.netlify/functions/hola
Content-Type: application/json

{
    "goal": "Ir a natación",
    "frequency": 6,
    "frequencyUnit": "Month",
    "target": 80,
    "icon": "👨‍💻",
    "id": 5,
    "count": 0
}

