GET http://localhost:8888/.netlify/functions/goalsAPI

###
POST http://localhost:8888/.netlify/functions/goalsAPI
Content-Type: application/json

{
    "goal": "Ir a natación",
    "frequency": 6,
    "frequencyUnit": "Month",
    "target": 80,
    "icon": "👨‍💻",
    "id": 5,
    "count": 0
}

###
PATCH http://localhost:8888/.netlify/functions/goalsAPI
Content-Type: application/json

{
    "id": "62713dae-efa9-49b7-a49f-6fdd0de4995c",
    "count": 7
}

